use serde::{Deserialize, Serialize};
use std::{collections::HashMap, fs, io::{Read, Write}, net::{IpAddr, Ipv4Addr, TcpListener, TcpStream, UdpSocket}, path::{Path, PathBuf}, sync::{Arc, Mutex}, thread, time::{Duration, Instant, SystemTime, UNIX_EPOCH}};
use tauri::{command, AppHandle, Emitter};
const DISCOVERY_PORT:u16=38947; const TRANSFER_PORT:u16=38948; const MAGIC:&str="SEAM_SHARE_DISCOVER_V2"; const CHUNK:usize=1024*256;
#[derive(Debug,Serialize,Clone)] pub struct NetworkInfo{pub local_ip:String,pub discovery_port:u16,pub transfer_port:u16}
#[derive(Debug,Serialize,Clone)] pub struct NearbyDevice{pub name:String,pub ip:String,pub port:u16}
#[derive(Debug,Serialize,Deserialize,Clone)] pub struct PairRequest{pub device_id:String,pub device_name:String,pub ip:String,pub port:u16,pub token:String}
#[derive(Debug,Serialize,Clone)] pub struct PairingInfo{pub device_id:String,pub device_name:String,pub ip:String,pub port:u16,pub token:String}
#[derive(Debug,Serialize,Clone)] pub struct PairedDeviceInfo{pub device_id:String,pub name:String,pub ip:String,pub port:u16,pub token:String}
#[derive(Debug,Serialize,Clone)] pub struct TransferProgress{pub id:String,pub name:String,pub sent:u64,pub total:u64,pub progress:u8,pub state:String}
#[derive(Debug,Serialize,Deserialize,Clone)] pub struct IncomingTransfer{pub id:String,pub name:String,pub size:u64,pub relative_path:String}
#[derive(Debug,Serialize,Deserialize,Clone)] struct PairedDevice{device_id:String,device_name:String,ip:String,port:u16,token:String}
#[derive(Debug,Serialize,Deserialize,Default)] struct Settings{receive_dir:Option<String>}
#[derive(Clone)] struct AppState{device_id:String,device_name:String,token:String,paired:Arc<Mutex<Vec<PairedDevice>>>,cancel:Arc<Mutex<Vec<String>>>,receive_dir:Arc<Mutex<PathBuf>>,pending:Arc<Mutex<HashMap<String,Option<bool>>>>}
fn local_ip()->Result<IpAddr,String>{local_ip_address::local_ip().map_err(|e|e.to_string())}
fn make_id()->String{format!("seam-{:x}",SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_nanos())}
fn default_receive_dir()->PathBuf{let mut p=PathBuf::from(std::env::var("USERPROFILE").unwrap_or_else(|_|".".into()));p.push("Downloads");p.push("SEAM Share");p}
fn settings_path()->PathBuf{let mut p=PathBuf::from(std::env::var("APPDATA").unwrap_or_else(|_|".".into()));p.push("SEAM Share");p.push("settings.json");p}
fn load_receive_dir()->PathBuf{let p=settings_path();fs::read_to_string(p).ok().and_then(|s|serde_json::from_str::<Settings>(&s).ok()).and_then(|s|s.receive_dir.map(PathBuf::from)).unwrap_or_else(default_receive_dir)}
fn save_receive_dir(path:&PathBuf)->Result<(),String>{let p=settings_path();if let Some(parent)=p.parent(){fs::create_dir_all(parent).map_err(|e|e.to_string())?}let data=serde_json::to_string_pretty(&Settings{receive_dir:Some(path.to_string_lossy().into_owned())}).map_err(|e|e.to_string())?;fs::write(p,data).map_err(|e|e.to_string())}
fn safe_segment(v:&str)->String{v.chars().filter(|c|c.is_alphanumeric()||matches!(c,'.'|'_'|'-'|' ')).collect::<String>().trim().to_string()}
fn safe_relative(v:&str)->PathBuf{v.replace("\\","/").split('/').filter_map(|s|{let x=safe_segment(s);if x.is_empty()||x=="."||x==".."{None}else{Some(x)}}).collect()}
fn header(h:&[(String,String)],k:&str)->Option<String>{h.iter().find(|(a,_)|a==k).map(|(_,b)|b.clone())}
#[command] fn network_info()->Result<NetworkInfo,String>{Ok(NetworkInfo{local_ip:local_ip()?.to_string(),discovery_port:DISCOVERY_PORT,transfer_port:TRANSFER_PORT})}
#[command] fn pairing_info(state:tauri::State<AppState>)->Result<PairingInfo,String>{Ok(PairingInfo{device_id:state.device_id.clone(),device_name:state.device_name.clone(),ip:local_ip()?.to_string(),port:TRANSFER_PORT,token:state.token.clone()})}
#[command] fn paired_devices(state:tauri::State<AppState>)->Result<Vec<PairedDeviceInfo>,String>{Ok(state.paired.lock().map_err(|_|"pairing state unavailable".to_string())?.iter().map(|p|PairedDeviceInfo{device_id:p.device_id.clone(),name:p.device_name.clone(),ip:p.ip.clone(),port:p.port,token:p.token.clone()}).collect())}
#[command] fn receive_directory(state:tauri::State<AppState>)->Result<String,String>{Ok(state.receive_dir.lock().map_err(|_|"settings unavailable".to_string())?.to_string_lossy().into_owned())}
#[command] fn set_receive_directory(path:String,state:tauri::State<AppState>)->Result<String,String>{let p=PathBuf::from(path);if !p.is_absolute(){return Err("Please choose an absolute folder path".into())}fs::create_dir_all(&p).map_err(|e|e.to_string())?;save_receive_dir(&p)?;*state.receive_dir.lock().map_err(|_|"settings unavailable".to_string())?=p.clone();Ok(p.to_string_lossy().into_owned())}
#[command] fn discover_devices(device_name:String,timeout_ms:u64)->Result<Vec<NearbyDevice>,String>{let socket=UdpSocket::bind((Ipv4Addr::UNSPECIFIED,0)).map_err(|e|e.to_string())?;socket.set_broadcast(true).map_err(|e|e.to_string())?;socket.set_read_timeout(Some(Duration::from_millis(150))).map_err(|e|e.to_string())?;let msg=format!("{}|{}|{}",MAGIC,device_name,TRANSFER_PORT);socket.send_to(msg.as_bytes(),(Ipv4Addr::BROADCAST,DISCOVERY_PORT)).map_err(|e|e.to_string())?;let deadline=Instant::now()+Duration::from_millis(timeout_ms.clamp(300,3000));let mut found=Vec::new();let mut buf=[0u8;1024];while Instant::now()<deadline{if let Ok((len,addr))=socket.recv_from(&mut buf){let text=String::from_utf8_lossy(&buf[..len]).to_string();let p:Vec<&str>=text.split('|').collect();if p.len()==3&&p[0]==MAGIC{if let Ok(port)=p[2].parse(){found.push(NearbyDevice{name:p[1].into(),ip:addr.ip().to_string(),port})}}}}found.sort_by(|a,b|a.ip.cmp(&b.ip));found.dedup_by(|a,b|a.ip==b.ip);Ok(found)}
fn run_discovery_responder(name:String){if let Ok(socket)=UdpSocket::bind((Ipv4Addr::UNSPECIFIED,DISCOVERY_PORT)){let mut buf=[0u8;1024];loop{if let Ok((len,addr))=socket.recv_from(&mut buf){let text=String::from_utf8_lossy(&buf[..len]).to_string();let p:Vec<&str>=text.split('|').collect();if p.len()>=3&&p[0]==MAGIC{let reply=format!("{}|{}|{}",MAGIC,name,TRANSFER_PORT);let _=socket.send_to(reply.as_bytes(),addr);}}}}}
fn read_headers(stream:&mut TcpStream)->Result<(String,Vec<(String,String)>,Vec<u8>),String>{let mut data=Vec::new();let mut buf=[0u8;4096];loop{let n=stream.read(&mut buf).map_err(|e|e.to_string())?;if n==0{return Err("connection closed".into())}data.extend_from_slice(&buf[..n]);if let Some(pos)=data.windows(4).position(|w|w==b"\r\n\r\n"){let text=String::from_utf8_lossy(&data[..pos+4]);let mut lines=text.split("\r\n");let request=lines.next().unwrap_or_default().to_string();let headers=lines.filter_map(|l|l.split_once(':')).map(|(k,v)|(k.trim().to_ascii_lowercase(),v.trim().to_string())).collect();return Ok((request,headers,data[pos+4..].to_vec()))}if data.len()>64*1024{return Err("headers too large".into())}}}
fn respond(stream:&mut TcpStream,code:u16,body:&str){let _=write!(stream,"HTTP/1.1 {} OK\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",code,body.len(),body);}
fn wait_approval(state:&AppState,app:&AppHandle,req:IncomingTransfer)->bool{if let Ok(mut p)=state.pending.lock(){p.insert(req.id.clone(),None);}let _=app.emit("incoming-transfer",req.clone());for _ in 0..240{thread::sleep(Duration::from_millis(500));if let Ok(mut p)=state.pending.lock(){if let Some(Some(v))=p.get(&req.id){let v=*v;p.remove(&req.id);return v}}}if let Ok(mut p)=state.pending.lock(){p.remove(&req.id);}false}
fn transfer_server(state:AppState,app:AppHandle){let listener=match TcpListener::bind((Ipv4Addr::UNSPECIFIED,TRANSFER_PORT)){Ok(v)=>v,Err(_)=>return};for incoming in listener.incoming(){if let Ok(mut stream)=incoming{let s=state.clone();let a=app.clone();thread::spawn(move||{let(request,headers,body)=match read_headers(&mut stream){Ok(v)=>v,Err(_)=>return};let token=header(&headers,"x-seam-token").unwrap_or_default();if token!=s.token{respond(&mut stream,401,"");return}if request.starts_with("POST /pair "){if let Ok(text)=String::from_utf8(body){if let Ok(pair)=serde_json::from_str::<PairRequest>(&text){if let Ok(mut list)=s.paired.lock(){list.retain(|p|p.device_id!=pair.device_id);list.push(PairedDevice{device_id:pair.device_id,device_name:pair.device_name,ip:pair.ip,port:pair.port,token:pair.token});}respond(&mut stream,200,"{}");return}}respond(&mut stream,400,"");return}if request.starts_with("POST /request "){if let Ok(text)=String::from_utf8(body){if let Ok(req)=serde_json::from_str::<IncomingTransfer>(&text){if wait_approval(&s,&a,req){respond(&mut stream,200,"OK")}else{respond(&mut stream,403,"DECLINED")}return}}respond(&mut stream,400,"");return}if request.starts_with("POST /receive "){let encoded=header(&headers,"x-file-name").unwrap_or_else(||"received-file".into());let name=percent_decode(&encoded);let size=header(&headers,"content-length").and_then(|v|v.parse::<u64>().ok()).unwrap_or(0);let relative=header(&headers,"x-relative-path").map(|v|percent_decode(&v)).unwrap_or(name.clone());let mut path=s.receive_dir.lock().map(|p|p.clone()).unwrap_or_else(|_|default_receive_dir());let rel=safe_relative(&relative);path.push(&rel);if rel.components().count()==0{respond(&mut stream,400,"");return}if let Some(parent)=path.parent(){let _=fs::create_dir_all(parent);}if let Ok(mut file)=fs::File::create(path){let mut total=body.len() as u64;let _=file.write_all(&body);let mut buf=[0u8;CHUNK];while total<size{match stream.read(&mut buf){Ok(0)=>break,Ok(n)=>{let _=file.write_all(&buf[..n]);total+=n as u64},Err(_)=>break}}respond(&mut stream,201,"OK");return}}respond(&mut stream,404,"")});}}}
fn percent_decode(v:&str)->String{let mut out=Vec::with_capacity(v.len());let b=v.as_bytes();let mut i=0;while i<b.len(){if b[i]==b'%'&&i+2<b.len(){if let Ok(x)=u8::from_str_radix(&v[i+1..i+3],16){out.push(x);i+=3;continue}}if b[i]==b'+'{out.push(b' ')}else{out.push(b[i])}i+=1}String::from_utf8_lossy(&out).into_owned()}
fn percent_encode(v:&str)->String{let mut s=String::new();for b in v.as_bytes(){if b.is_ascii_alphanumeric()||matches!(*b,b'.'|b'_'|b'-'|b'/'){s.push(*b as char)}else{use std::fmt::Write;write!(&mut s,"%{:02X}",b).ok();}}s}
#[command] fn approve_incoming(id:String,approved:bool,state:tauri::State<AppState>)->Result<(),String>{let mut p=state.pending.lock().map_err(|_|"approval state unavailable".to_string())?;if let Some(v)=p.get_mut(&id){*v=Some(approved);Ok(())}else{Err("transfer request expired".into())}}
#[command] fn list_files(path:String)->Result<Vec<(String,u64)>,String>{fn walk(root:&Path,dir:&Path,out:&mut Vec<(String,u64)>)->std::io::Result<()>{for e in fs::read_dir(dir)?{let e=e?;let p=e.path();if p.is_dir(){walk(root,&p,out)?}else if p.is_file(){if let Ok(rel)=p.strip_prefix(root){out.push((rel.to_string_lossy().into_owned(),e.metadata()?.len()))}}}Ok(())}let root=PathBuf::from(path);if !root.is_dir(){return Err("Not a folder".into())}let mut out=Vec::new();walk(&root,&root,&mut out).map_err(|e|e.to_string())?;Ok(out)}
#[command] fn cancel_transfer(id:String,state:tauri::State<AppState>)->Result<(),String>{if let Ok(mut c)=state.cancel.lock(){if !c.contains(&id){c.push(id)}}Ok(())}
#[command] fn send_file(app:AppHandle,state:tauri::State<AppState>,path:String,ip:String,port:u16,token:String,id:String,relative_path:Option<String>)->Result<(),String>{let total=fs::metadata(&path).map_err(|e|e.to_string())?.len();let name=PathBuf::from(&path).file_name().and_then(|v|v.to_str()).unwrap_or("shared-file").to_string();let rel=relative_path.unwrap_or_else(||name.clone());let addr=format!("{}:{}",ip,port);let mut stream=TcpStream::connect(&addr).map_err(|e|e.to_string())?;stream.set_read_timeout(Some(Duration::from_secs(125))).ok();let req=IncomingTransfer{id:id.clone(),name:name.clone(),size:total,relative_path:rel.clone()};let body=serde_json::to_string(&req).map_err(|e|e.to_string())?;let head=format!("POST /request HTTP/1.1\r\nHost: {}\r\nContent-Length: {}\r\nContent-Type: application/json\r\nX-Seam-Token: {}\r\nConnection: close\r\n\r\n{}",addr,body.len(),token,body);stream.write_all(head.as_bytes()).map_err(|e|e.to_string())?;let mut approval=[0u8;512];let n=stream.read(&mut approval).map_err(|e|e.to_string())?;let response=String::from_utf8_lossy(&approval[..n]);if !response.contains(" 200 "){return Err("Transfer declined".into())}drop(stream);let mut stream=TcpStream::connect(&addr).map_err(|e|e.to_string())?;let enc=percent_encode(&rel);let head=format!("POST /receive HTTP/1.1\r\nHost: {}\r\nContent-Length: {}\r\nContent-Type: application/octet-stream\r\nX-Seam-Token: {}\r\nX-File-Name: {}\r\nX-Relative-Path: {}\r\nConnection: close\r\n\r\n",addr,total,token,enc,enc);stream.write_all(head.as_bytes()).map_err(|e|e.to_string())?;let mut file=fs::File::open(&path).map_err(|e|e.to_string())?;let mut buf=[0u8;CHUNK];let mut sent=0u64;loop{if state.cancel.lock().map(|c|c.contains(&id)).unwrap_or(false){let _=app.emit("transfer-progress",TransferProgress{id:id.clone(),name:name.clone(),sent,total,progress:((sent*100)/total.max(1)) as u8,state:"cancelled".into()});return Ok(())}let n=file.read(&mut buf).map_err(|e|e.to_string())?;if n==0{break}stream.write_all(&buf[..n]).map_err(|e|e.to_string())?;sent+=n as u64;let _=app.emit("transfer-progress",TransferProgress{id:id.clone(),name:name.clone(),sent,total,progress:((sent*100)/total.max(1)) as u8,state:"sending".into()});}let mut response=[0u8;256];let _=stream.read(&mut response);let _=app.emit("transfer-progress",TransferProgress{id,name,sent:total,total,progress:100,state:"complete".into()});Ok(())}
#[cfg_attr(mobile,tauri::mobile_entry_point)] pub fn run(){let receive_dir=load_receive_dir();let _=fs::create_dir_all(&receive_dir);let state=AppState{device_id:make_id(),device_name:"This PC".into(),token:make_id(),paired:Arc::new(Mutex::new(Vec::new())),cancel:Arc::new(Mutex::new(Vec::new())),receive_dir:Arc::new(Mutex::new(receive_dir)),pending:Arc::new(Mutex::new(HashMap::new()))};let d=state.device_name.clone();thread::spawn(move||run_discovery_responder(d));tauri::Builder::default().plugin(tauri_plugin_dialog::init()).manage(state.clone()).setup(move|app|{let h=app.handle().clone();let s=state.clone();thread::spawn(move||transfer_server(s,h));Ok(())}).invoke_handler(tauri::generate_handler![network_info,discover_devices,pairing_info,paired_devices,send_file,cancel_transfer,receive_directory,set_receive_directory,list_files,approve_incoming]).run(tauri::generate_context!()).expect("error while running tauri application")}
