use serde::{Deserialize, Serialize};
use std::{fs, io::{Read, Write}, net::{IpAddr, Ipv4Addr, TcpListener, TcpStream, UdpSocket}, path::PathBuf, sync::{Arc, Mutex}, thread, time::{Duration, Instant, SystemTime, UNIX_EPOCH}};
use tauri::{command, AppHandle, Emitter};

const DISCOVERY_PORT:u16=38947; const TRANSFER_PORT:u16=38948; const MAGIC:&str="SEAM_SHARE_DISCOVER_V2"; const CHUNK:usize=1024*256;
#[derive(Debug,Serialize,Clone)] pub struct NetworkInfo{pub local_ip:String,pub discovery_port:u16,pub transfer_port:u16}
#[derive(Debug,Serialize,Clone)] pub struct NearbyDevice{pub name:String,pub ip:String,pub port:u16}
#[derive(Debug,Serialize,Deserialize,Clone)] pub struct PairRequest{pub device_id:String,pub device_name:String,pub ip:String,pub port:u16,pub token:String}
#[derive(Debug,Serialize,Clone)] pub struct PairingInfo{pub device_id:String,pub device_name:String,pub ip:String,pub port:u16,pub token:String}
#[derive(Debug,Serialize,Clone)] pub struct TransferProgress{pub id:String,pub name:String,pub sent:u64,pub total:u64,pub progress:u8,state:String}
#[derive(Debug,Serialize,Deserialize,Clone)] struct PairedDevice{device_id:String,device_name:String,ip:String,port:u16,token:String}
#[derive(Clone)] struct AppState{device_id:String,device_name:String,token:String,paired:Arc<Mutex<Vec<PairedDevice>>>,cancel:Arc<Mutex<Vec<String>>>}
fn local_ip()->Result<IpAddr,String>{local_ip_address::local_ip().map_err(|e|e.to_string())} fn make_id()->String{format!("seam-{:x}",SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_nanos())}
fn safe_filename(v:&str)->String{let s=v.chars().filter(|c|c.is_ascii_alphanumeric()||matches!(c,'.'|'_'|'-'|' ')).collect::<String>();if s.is_empty(){"received-file".into()}else{s}}
fn header(h:&[(String,String)],k:&str)->Option<String>{h.iter().find(|(a,_)|a==k).map(|(_,b)|b.clone())}
#[command] fn network_info()->Result<NetworkInfo,String>{Ok(NetworkInfo{local_ip:local_ip()?.to_string(),discovery_port:DISCOVERY_PORT,transfer_port:TRANSFER_PORT})}
#[command] fn pairing_info(state:tauri::State<AppState>)->Result<PairingInfo,String>{Ok(PairingInfo{device_id:state.device_id.clone(),device_name:state.device_name.clone(),ip:local_ip()?.to_string(),port:TRANSFER_PORT,token:state.token.clone()})}
#[command] fn paired_devices(state:tauri::State<AppState>)->Result<Vec<NearbyDevice>,String>{Ok(state.paired.lock().map_err(|_|"pairing state unavailable".to_string())?.iter().map(|p|NearbyDevice{name:p.device_name.clone(),ip:p.ip.clone(),port:p.port}).collect())}
#[command] fn discover_devices(device_name:String,timeout_ms:u64)->Result<Vec<NearbyDevice>,String>{let socket=UdpSocket::bind((Ipv4Addr::UNSPECIFIED,0)).map_err(|e|e.to_string())?;socket.set_broadcast(true).map_err(|e|e.to_string())?;socket.set_read_timeout(Some(Duration::from_millis(150))).map_err(|e|e.to_string())?;let msg=format!("{}|{}|{}",MAGIC,device_name,TRANSFER_PORT);socket.send_to(msg.as_bytes(),(Ipv4Addr::BROADCAST,DISCOVERY_PORT)).map_err(|e|e.to_string())?;let deadline=Instant::now()+Duration::from_millis(timeout_ms.clamp(300,3000));let mut found=Vec::new();let mut buf=[0u8;1024];while Instant::now()<deadline{if let Ok((len,addr))=socket.recv_from(&mut buf){let p:Vec<&str>=String::from_utf8_lossy(&buf[..len]).split('|').collect();if p.len()==3&&p[0]==MAGIC{if let Ok(port)=p[2].parse(){found.push(NearbyDevice{name:p[1].into(),ip:addr.ip().to_string(),port})}}}}found.sort_by(|a,b|a.ip.cmp(&b.ip));found.dedup_by(|a,b|a.ip==b.ip);Ok(found)}
fn run_discovery_responder(name:String){if let Ok(socket)=UdpSocket::bind((Ipv4Addr::UNSPECIFIED,DISCOVERY_PORT)){let mut buf=[0u8;1024];loop{if let Ok((len,addr))=socket.recv_from(&mut buf){let p:Vec<&str>=String::from_utf8_lossy(&buf[..len]).split('|').collect();if p.len()>=3&&p[0]==MAGIC{let reply=format!("{}|{}|{}",MAGIC,name,TRANSFER_PORT);let _=socket.send_to(reply.as_bytes(),addr)}}}}}
fn read_headers(stream:&mut TcpStream)->Result<(String,Vec<(String,String)>,Vec<u8>),String>{let mut data=Vec::new();let mut buf=[0u8;4096];loop{let n=stream.read(&mut buf).map_err(|e|e.to_string())?;if n==0{return Err("connection closed".into())}data.extend_from_slice(&buf[..n]);if let Some(pos)=data.windows(4).position(|w|w==b"\r\n\r\n"){let text=String::from_utf8_lossy(&data[..pos+4]);let mut lines=text.split("\r\n");let request=lines.next().unwrap_or_default().to_string();let headers=lines.filter_map(|l|l.split_once(':')).map(|(k,v)|(k.trim().to_ascii_lowercase(),v.trim().to_string())).collect();return Ok((request,headers,data[pos+4..].to_vec()))}if data.len()>64*1024{return Err("headers too large".into())}}}
fn transfer_server(state:AppState){let listener=match TcpListener::bind((Ipv4Addr::UNSPECIFIED,TRANSFER_PORT)){Ok(v)=>v,Err(_)=>return};for incoming in listener.incoming(){if let Ok(mut stream)=incoming{let s=state.clone();thread::spawn(move||{let(request,headers,body)=match read_headers(&mut stream){Ok(v)=>v,Err(_)=>return};let token=header(&headers,"x-seam-token").unwrap_or_default();if token!=s.token{let _=stream.write_all(b"HTTP/1.1 401 Unauthorized\r\nContent-Length: 0\r\n\r\n");return}if request.starts_with("POST /pair "){if let Ok(text)=String::from_utf8(body){if let Ok(pair)=serde_json::from_str::<PairRequest>(&text){if let Ok(mut list)=s.paired.lock(){list.retain(|p|p.device_id!=pair.device_id);list.push(PairedDevice{device_id:pair.device_id,device_name:pair.device_name,ip:pair.ip,port:pair.port,token:pair.token});}let _=stream.write_all(b"HTTP/1.1 200 OK\r\nContent-Length: 2\r\nContent-Type: application/json\r\n\r\n{} ");return}}}let _=stream.write_all(b"HTTP/1.1 400 Bad Request\r\nContent-Length: 0\r\n\r\n");return}if request.starts_with("POST /receive "){let name=header(&headers,"x-file-name").unwrap_or_else(||"received-file".into());let size=header(&headers,"content-length").and_then(|v|v.parse::<u64>().ok()).unwrap_or(0);let mut path=PathBuf::from(std::env::var("USERPROFILE").unwrap_or_else(|_|".".into()));path.push("Downloads");path.push("SEAM Share");let _=fs::create_dir_all(&path);path.push(safe_filename(&name));if let Ok(mut file)=fs::File::create(path){let mut total=body.len() as u64;let _=file.write_all(&body);let mut buf=[0u8;CHUNK];while total<size{match stream.read(&mut buf){Ok(0)=>break,Ok(n)=>{let _=file.write_all(&buf[..n]);total+=n as u64},Err(_)=>break}}let _=stream.write_all(b"HTTP/1.1 201 Created\r\nContent-Length: 2\r\n\r\nOK");return}}let _=stream.write_all(b"HTTP/1.1 404 Not Found\r\nContent-Length: 0\r\n\r\n")})}}}}
#[command] fn cancel_transfer(id:String,state:tauri::State<AppState>)->Result<(),String>{if let Ok(mut c)=state.cancel.lock(){if !c.contains(&id){c.push(id)}}Ok(())}
#[command] fn send_file(app:AppHandle,state:tauri::State<AppState>,path:String,ip:String,port:u16,token:String,id:String)->Result<(),String>{let total=fs::metadata(&path).map_err(|e|e.to_string())?.len();let name=PathBuf::from(&path).file_name().and_then(|v|v.to_str()).unwrap_or("shared-file").to_string();let addr=format!("{}:{}",ip,port);let mut stream=TcpStream::connect(&addr).map_err(|e|e.to_string())?;stream.set_write_timeout(Some(Duration::from_secs(10))).ok();let head=format!("POST /receive HTTP/1.1\r\nHost: {}\r\nContent-Length: {}\r\nContent-Type: application/octet-stream\r\nX-Seam-Token: {}\r\nX-File-Name: {}\r\nConnection: close\r\n\r\n",addr,total,token,urlencoding::encode(&name));stream.write_all(head.as_bytes()).map_err(|e|e.to_string())?;let mut file=fs::File::open(&path).map_err(|e|e.to_string())?;let mut buf=[0u8;CHUNK];let mut sent=0u64;loop{if state.cancel.lock().map(|c|c.contains(&id)).unwrap_or(false){let _=app.emit("transfer-progress",TransferProgress{id:id.clone(),name:name.clone(),sent,total,progress:((sent*100)/total.max(1)) as u8,state:"cancelled".into()});return Ok(())}let n=file.read(&mut buf).map_err(|e|e.to_string())?;if n==0{break}stream.write_all(&buf[..n]).map_err(|e|e.to_string())?;sent+=n as u64;let _=app.emit("transfer-progress",TransferProgress{id:id.clone(),name:name.clone(),sent,total,progress:((sent*100)/total.max(1)) as u8,state:"sending".into()});}let mut response=[0u8;256];let _=stream.read(&mut response);let _=app.emit("transfer-progress",TransferProgress{id,name,sent:total,total,progress:100,state:"complete".into()});Ok(())}
#[cfg_attr(mobile,tauri::mobile_entry_point)] pub fn run(){let state=AppState{device_id:make_id(),device_name:"This PC".into(),token:make_id(),paired:Arc::new(Mutex::new(Vec::new())),cancel:Arc::new(Mutex::new(Vec::new()))};let d=state.device_name.clone();let t=state.clone();thread::spawn(move||run_discovery_responder(d));thread::spawn(move||transfer_server(t));tauri::Builder::default().plugin(tauri_plugin_dialog::init()).manage(state).invoke_handler(tauri::generate_handler![network_info,discover_devices,pairing_info,paired_devices,send_file,cancel_transfer]).run(tauri::generate_context!()).expect("error while running tauri application")}
