import { useEffect, useRef, useState } from 'react'
import { invoke } from '@tauri-apps/api/core'
import { CheckCircle2, ChevronRight, FileText, FolderOpen, Link2, MoreHorizontal, Monitor, Plus, RefreshCw, Send, Smartphone, UploadCloud, Wifi } from 'lucide-react'

type Device = { name: string; ip: string; port: number }
type PairingInfo = { device_id:string; device_name:string; ip:string; port:number; token:string }

type Transfer = { name:string; size:string; time:string; state:string }

export default function App() {
  const input = useRef<HTMLInputElement>(null)
  const [dragging,setDragging]=useState(false), [selected,setSelected]=useState<File|null>(null), [devices,setDevices]=useState<Device[]>([]), [scanning,setScanning]=useState(false), [localIp,setLocalIp]=useState('Local network'), [pairing,setPairing]=useState<PairingInfo|null>(null), [message,setMessage]=useState('')
  const [history,setHistory]=useState<Transfer[]>([])
  const pick=()=>input.current?.click()
  const files=(list:FileList|null)=>{const file=list?.[0];if(file)setSelected(file)}
  const scan=async()=>{setScanning(true);setMessage('');try{const info=await invoke<{local_ip:string}>('network_info');setLocalIp(info.local_ip);setDevices(await invoke<Device[]>('discover_devices',{deviceName:"Sepehr's PC",timeoutMs:1200}))}catch{setDevices([]);setMessage('Network scan failed')}finally{setScanning(false)}}
  const showPairing=async()=>{try{setPairing(await invoke<PairingInfo>('pairing_info'))}catch{setMessage('Native service is not running')}}
  useEffect(()=>{scan()},[])
  const send=async()=>{if(!selected||!devices[0]){setMessage('Select a file and a nearby device first');return}setMessage('Transfer protocol is ready — Android receiver will complete this link.');setHistory(h=>[{name:selected.name,size:`${(selected.size/1024/1024).toFixed(1)} MB`,time:'Just now',state:'Ready'},...h].slice(0,5))}
  return <main className="shell"><div className="glow glow-a"/><div className="glow glow-b"/>
    <header className="topbar"><div className="brand"><img src="/assets/seam-share-logo.svg"/><div><strong>SEAM Share</strong><span>Move freely. Stay connected.</span></div></div><div className="status"><i/><span>Ready to share</span><button aria-label="More"><MoreHorizontal size={18}/></button></div></header>
    <section className="hero"><div className="hero-copy"><h1>Share without<br/><em>the friction.</em></h1><p>Send files, photos and text between your devices. Fast, private, effortless.</p></div><div className="space-card"><div className="space-orbit"><div className="orbit-ring ring-1"/><div className="orbit-ring ring-2"/><div className="device-pill phone"><Smartphone size={20}/><span>Android</span></div><div className="device-pill pc"><Monitor size={20}/><span>This PC</span></div><div className="center-logo"><Wifi size={27}/></div></div></div></section>
    <section className="workspace"><div className={`dropzone ${dragging?'dragging':''}`} onClick={pick} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);files(e.dataTransfer.files)}}><input ref={input} hidden type="file" multiple onChange={e=>files(e.target.files)}/><div className="drop-icon"><UploadCloud size={28}/></div><h2>{selected?.name??'Drop anything here'}</h2><p>{selected?`${(selected.size/1024/1024).toFixed(1)} MB · ready to send`:'Drag & drop files, or click to browse'}</p><div className="drop-actions"><button className="primary" onClick={e=>{e.stopPropagation();pick()}}><Plus size={17}/> Choose files</button>{selected&&devices.length>0&&<button className="primary" onClick={e=>{e.stopPropagation();void send()}}><Send size={16}/> Send</button>}<span><Link2 size={14}/> Private connection</span></div></div>
      <aside className="side"><div className="side-head"><div><span className="eyebrow">NEARBY</span><h3>Your devices</h3></div><div><button aria-label="Pair" onClick={showPairing}><Link2 size={15}/></button><button aria-label="Scan" onClick={scan}><RefreshCw size={16} className={scanning?'spin':''}/></button></div></div>{devices.length?devices.map(d=><div className="device active" key={d.ip}><div className="device-icon"><Smartphone size={20}/></div><div className="device-info"><strong>{d.name}</strong><span><i/> {d.ip}:{d.port}</span></div><ChevronRight size={17}/></div>):<div className="empty-device"><Smartphone size={20}/><span>{scanning?'Scanning your network…':'No devices found yet'}<small>Tap ↻ to scan nearby devices</small></span></div>}<div className="privacy"><div><Wifi size={18}/></div><span><strong>Local & private</strong><small>{localIp} · transfers stay on your network.</small></span></div>{message&&<div className="notice">{message}</div>}{pairing&&<div className="pair-card"><strong>Pair this PC</strong><code>{JSON.stringify(pairing)}</code><button className="primary" onClick={()=>navigator.clipboard?.writeText(JSON.stringify(pairing))}>Copy pairing code</button></div>}</aside></section>
    <section className="recent"><div className="recent-head"><div><span className="eyebrow">ACTIVITY</span><h3>Recent transfers</h3></div><button>View all <ChevronRight size={15}/></button></div><div className="transfer-list">{history.length?history.map((t,i)=><div className="transfer" key={`${t.name}-${i}`}><div className="file-icon"><FolderOpen size={18}/></div><div className="file-meta"><strong>{t.name}</strong><span>{t.size} · {t.time}</span></div><div className="transfer-state"><CheckCircle2 size={17}/><span>{t.state}</span></div><Send size={16}/></div>):<div className="empty-history">No transfers in this session yet.</div>}</div></section>
    <footer><span>SEAM Share 0.1</span><span>Connected via local network · {localIp}</span></footer></main>
}
