import { useEffect, useRef, useState } from 'react'
import { invoke } from '@tauri-apps/api/core'
import { listen } from '@tauri-apps/api/event'
import { open } from '@tauri-apps/plugin-dialog'
import { CheckCircle2, ChevronRight, FileText, FolderOpen, Link2, MoreHorizontal, Monitor, Plus, RefreshCw, Send, Smartphone, UploadCloud, Wifi, X } from 'lucide-react'
import { pairingQrDataUrl } from './lib/qr'

type Device={name:string;ip:string;port:number}
type PairingInfo={device_id:string;device_name:string;ip:string;port:number;token:string}
type Paired={device_id:string;name:string;ip:string;port:number;token:string}
type Transfer={name:string;size:string;time:string;state:string}
type Progress={id:string;name:string;sent:number;total:number;progress:number;state:string}

export default function App(){
 const [devices,setDevices]=useState<Device[]>([]),[paired,setPaired]=useState<Paired[]>([]),[scanning,setScanning]=useState(false),[localIp,setLocalIp]=useState('Local network'),[pairing,setPairing]=useState<PairingInfo|null>(null),[qr,setQr]=useState(''),[message,setMessage]=useState(''),[selectedPath,setSelectedPath]=useState<string|null>(null),[selectedName,setSelectedName]=useState(''),[progress,setProgress]=useState<Progress|null>(null),[history,setHistory]=useState<Transfer[]>([])
 const scan=async()=>{setScanning(true);try{const info=await invoke<{local_ip:string}>('network_info');setLocalIp(info.local_ip);setDevices(await invoke<Device[]>('discover_devices',{deviceName:"This PC",timeoutMs:1200}));setPaired(await invoke<Paired[]>('paired_devices'))}catch{setMessage('Network scan failed')}finally{setScanning(false)}}
 const showPairing=async()=>{try{const info=await invoke<PairingInfo>('pairing_info');setPairing(info);setQr(await pairingQrDataUrl(info))}catch{setMessage('Native service is not running')}}
 useEffect(()=>{void scan();const unlisten=listen<Progress>('transfer-progress',e=>{setProgress(e.payload);if(e.payload.state==='complete'){setHistory(h=>[{name:e.payload.name,size:`${(e.payload.total/1024/1024).toFixed(1)} MB`,time:'Just now',state:'Sent'},...h].slice(0,5));setMessage('Transfer complete')}if(e.payload.state==='cancelled')setMessage('Transfer cancelled')});return()=>{void unlisten}},[])
 const choose=async()=>{const file=await open({multiple:false,directory:false,title:'Choose a file to share'});if(typeof file==='string'){setSelectedPath(file);setSelectedName(file.split(/[\\/]/).pop()||file);setMessage('File ready to share')}}
 const send=async()=>{if(!selectedPath){setMessage('Choose a file first');return}const target=paired[0]||null;if(!target){setMessage('Scan the Android QR first to pair this PC');return}const id=crypto.randomUUID();setProgress({id,name:selectedName,sent:0,total:0,progress:0,state:'sending'});try{await invoke('send_file',{path:selectedPath,ip:target.ip,port:target.port,token:target.token,id})}catch(e){setMessage(`Transfer failed: ${String(e)}`);setProgress(null)}}
 const cancel=async()=>{if(progress?.state==='sending'){await invoke('cancel_transfer',{id:progress.id});}}
 return <main className="shell"><div className="glow glow-a"/><div className="glow glow-b"/>
 <header className="topbar"><div className="brand"><img src="/assets/seam-share-logo.svg"/><div><strong>SEAM Share</strong><span>Move freely. Stay connected.</span></div></div><div className="status"><i/><span>Ready to share</span><button aria-label="More"><MoreHorizontal size={18}/></button></div></header>
 <section className="hero"><div className="hero-copy"><h1>Share without<br/><em>the friction.</em></h1><p>Send files, photos and text between your devices. Fast, private, effortless.</p></div><div className="space-card"><div className="space-orbit"><div className="orbit-ring ring-1"/><div className="orbit-ring ring-2"/><div className="device-pill phone"><Smartphone size={20}/><span>Android</span></div><div className="device-pill pc"><Monitor size={20}/><span>This PC</span></div><div className="center-logo"><Wifi size={27}/></div></div></div></section>
 <section className="workspace"><div className="dropzone" onClick={choose}><div className="drop-icon"><UploadCloud size={28}/></div><h2>{selectedName||'Drop anything here'}</h2><p>{selectedPath?'Ready to send from Windows':'Click to choose a file'}</p><div className="drop-actions"><button className="primary" onClick={e=>{e.stopPropagation();void choose()}}><Plus size={17}/> Choose file</button>{selectedPath&&<button className="primary" onClick={e=>{e.stopPropagation();void send()}}><Send size={16}/> Send</button>}<span><Link2 size={14}/> Private connection</span></div></div>
 <aside className="side"><div className="side-head"><div><span className="eyebrow">NEARBY</span><h3>Your devices</h3></div><div><button aria-label="Pair" onClick={showPairing}><Link2 size={15}/></button><button aria-label="Scan" onClick={()=>void scan()}><RefreshCw size={16} className={scanning?'spin':''}/></button></div></div>{paired.length?paired.map(d=><div className="device active" key={d.device_id}><div className="device-icon"><Smartphone size={20}/></div><div className="device-info"><strong>{d.name}</strong><span><i/> Paired · {d.ip}:{d.port}</span></div><ChevronRight size={17}/></div>):devices.length?devices.map(d=><div className="device active" key={d.ip}><div className="device-icon"><Smartphone size={20}/></div><div className="device-info"><strong>{d.name}</strong><span><i/> {d.ip}:{d.port} · scan QR to pair</span></div></div>):<div className="empty-device"><Smartphone size={20}/><span>{scanning?'Scanning your network…':'No devices found yet'}<small>Tap ↻ to scan nearby devices</small></span></div>}<div className="privacy"><div><Wifi size={18}/></div><span><strong>Local & private</strong><small>{localIp} · transfers stay on your network.</small></span></div>{message&&<div className="notice">{message}</div>}{progress&&progress.state==='sending'&&<div className="pair-card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><strong>Sending {progress.name}</strong><button onClick={()=>void cancel()} aria-label="Cancel"><X size={16}/></button></div><progress max={100} value={progress.progress} style={{width:'100%',marginTop:12}}/><small>{progress.progress}% · {(progress.sent/1024/1024).toFixed(1)} / {(progress.total/1024/1024).toFixed(1)} MB</small></div>}{pairing&&<div className="pair-card"><strong>Scan to pair Android</strong>{qr&&<img src={qr} alt="SEAM Share pairing QR code" style={{width:180,height:180,borderRadius:16,background:'#fff',padding:8}}/>}<small>Scan this QR from SEAM Share on Android. Pairing enables two-way local transfers.</small><button className="primary" onClick={()=>navigator.clipboard?.writeText(JSON.stringify(pairing))}>Copy pairing code</button></div>}</aside></section>
 <section className="recent"><div className="recent-head"><div><span className="eyebrow">ACTIVITY</span><h3>Recent transfers</h3></div><button>View all <ChevronRight size={15}/></button></div><div className="transfer-list">{history.length?history.map((t,i)=><div className="transfer" key={`${t.name}-${i}`}><div className="file-icon"><FolderOpen size={18}/></div><div className="file-meta"><strong>{t.name}</strong><span>{t.size} · {t.time}</span></div><div className="transfer-state"><CheckCircle2 size={17}/><span>{t.state}</span></div><Send size={16}/></div>):<div className="empty-history">No transfers in this session yet.</div>}</div></section><footer><span>SEAM Share 0.1</span><span>Connected via local network · {localIp}</span></footer></main>
}
